language: python
sudo: false
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
install:
    - travis_retry pip install tox
script:
    - tox
notifications:
    email: false
